version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DB_PORT=5432
      - DB_HOST=172.22.0.3
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=db_app
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,172.22.0.4
      - PYTHONPATH=app
    networks:
      app_network:
        ipv4_address: 172.22.0.2


  db:
    image: postgres:15.0-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db_app'
    networks:
      app_network:
        ipv4_address: 172.22.0.3

  web-server:
    image: nginx
    container_name: server
    ports:
      - '81:80'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/crudTest/static:/usr/share/nginx/static
    networks:
      app_network:
        ipv4_address: 172.22.0.4

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16