version: '3.1'

services:

  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'db_app'
    ports:
      - '5430:5432'